// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'componentBox': string;
  'img': string;
  'imgBox': string;
  'infoAuthor': string;
  'infoAuthourHeaderEnd': string;
  'infoAuthourHeaderStart': string;
  'infoAuthourValue': string;
  'infoBox': string;
  'infoTitle': string;
  'infoTitleHeaderEnd': string;
  'infoTitleHeaderStart': string;
  'infoTitleValue': string;
}
export const cssExports: CssExports;
export default cssExports;
